/**
 * SlidEnglish
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExampleOfUse { 
    id?: number;
    example: string;
    attribute?: ExampleOfUse.AttributeEnum;
}
export namespace ExampleOfUse {
    export type AttributeEnum = 0 | 1 | 2;
    export const AttributeEnum = {
        NUMBER_0: 0 as AttributeEnum,
        NUMBER_1: 1 as AttributeEnum,
        NUMBER_2: 2 as AttributeEnum
    };
}
