/**
 * SlidEnglish
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExampleOfUse } from './exampleOfUse';
import { LexicalUnitRelation } from './lexicalUnitRelation';


export interface LexicalUnit { 
    id?: number;
    text: string;
    association?: string;
    notes?: string;
    relatedLexicalUnits?: Array<LexicalUnitRelation>;
    inputAttributes?: LexicalUnit.InputAttributesEnum;
    usagesCount?: number;
    partOfSpeech?: LexicalUnit.PartOfSpeechEnum;
    examplesOfUse?: Array<ExampleOfUse>;
    isWord?: boolean;
    isPhrase?: boolean;
}
export namespace LexicalUnit {
    export type InputAttributesEnum = 0 | 1 | 2;
    export const InputAttributesEnum = {
        NUMBER_0: 0 as InputAttributesEnum,
        NUMBER_1: 1 as InputAttributesEnum,
        NUMBER_2: 2 as InputAttributesEnum
    };
    export type PartOfSpeechEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6;
    export const PartOfSpeechEnum = {
        NUMBER_0: 0 as PartOfSpeechEnum,
        NUMBER_1: 1 as PartOfSpeechEnum,
        NUMBER_2: 2 as PartOfSpeechEnum,
        NUMBER_3: 3 as PartOfSpeechEnum,
        NUMBER_4: 4 as PartOfSpeechEnum,
        NUMBER_5: 5 as PartOfSpeechEnum,
        NUMBER_6: 6 as PartOfSpeechEnum
    };
}
