/**
 * SlidEnglish
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type PartOfSpeech = 'None' | 'Verb' | 'Noun' | 'Adjective' | 'Preposition' | 'Pronoun' | 'Article';

export const PartOfSpeech = {
    None: 'None' as PartOfSpeech,
    Verb: 'Verb' as PartOfSpeech,
    Noun: 'Noun' as PartOfSpeech,
    Adjective: 'Adjective' as PartOfSpeech,
    Preposition: 'Preposition' as PartOfSpeech,
    Pronoun: 'Pronoun' as PartOfSpeech,
    Article: 'Article' as PartOfSpeech
};
